_target_: HMW1_2025.training.w2v_cultural_trainer.W2VCulturalTrainer
model: ${model}
train_dataset: ${train_dataset}
validation_dataset: ${validation_dataset}
output_dir: ${output_dir}
learning_rate: ${learning_rate}
num_epochs: ${num_epochs}
device_name: ${device_name}
batch_size: ${batch_size}
collator: ${collator}